### ISSUE TITLE
Ton reader not working

### ISSUE THREAD

**Issue by rustam87** [tact-lang/tact-template#11]
TSError: ⨯ Unable to compile TypeScript:
sources/contract.read.ts:3:54 - error TS2307: Cannot find module 'ton' or its corresponding type declarations.

import { Address, contractAddress, TonClient4 } from "ton";
                                                       ~~~~~



![Screenshot from 2024-01-11 11-30-17](https://github.com/tact-lang/tact-template/assets/16744441/df8cd98b-9c75-4cdc-934e-123878e0d94c)


How can I create PR?
Github sad me "ERROR: Permission to tact-lang/tact-template.git denied"

**Comment by anton-trunov** [comment]
@rustam87 You need to create your own fork of `tact-template`, make your changes in the fork and then open a PR

**Comment by anton-trunov** [comment]
@rustam87 Could you specify what kind of error you observe? If you could copy and paste it in the original post that would be very much appreciated
