### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by StevenGaoGithub** [tact-lang/tact-template#21]
I run the code but the deployment fails

![image](https://github.com/tact-lang/tact-template/assets/168339500/ab7027e3-ff5e-4ef8-bbc0-4db2ebc6dbee)
![image](https://github.com/tact-lang/tact-template/assets/168339500/60fd0d65-7fbc-425f-9177-af3bcab87ed9)

url connect time out

**Comment by anton-trunov** [comment]
Please make sure this is not a network issue and re-open the issue
