### ISSUE TITLE
Critical error. Deployment failed.

### ISSUE THREAD

**Issue by ldbchang** [tact-lang/tact-template#24]
Error location: contract.deploy.ts
let prepare = await prepareTactDeployment({ pkg, data, testnet });

  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
AxiosError [AggregateError]
    at Function.AxiosError.from (D:\01-Blockchain\21-ton\01-tact\00-SVN\01-All\node_modules\axios\lib\core\AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (D:\01-Blockchain\21-ton\01-tact\00-SVN\01-All\node_modules\axios\lib\adapters\http.js:610:25)
    at RedirectableRequest.emit (node:events:531:35)
    at RedirectableRequest.emit (node:domain:488:12)
    at ClientRequest.eventHandlers.<computed> (D:\01-Blockchain\21-ton\01-tact\00-SVN\01-All\node_modules\follow-redirects\index.js:38:24)
    at ClientRequest.emit (node:events:519:28)
    at ClientRequest.emit (node:domain:488:12)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket.emit (node:domain:488:12)
    at Axios.request (D:\01-Blockchain\21-ton\01-tact\00-SVN\01-All\node_modules\axios\lib\core\Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async prepareTactDeployment (D:\01-Blockchain\21-ton\01-tact\00-SVN\01-All\sources\deploy\deployer.ts:48:15)
    at async D:\01-Blockchain\21-ton\01-tact\00-SVN\01-All\sources\contract.deploy.ts:21:19 {
  code: 'ETIMEDOUT',
  errors: [
    Error: connect ETIMEDOUT 2a03:2880:f11c:8083:face:b00c:0:25de:443
        at createConnectionError (node:net:1647:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1706:38)
        at listOnTimeout (node:internal/timers:575:11)
        at processTimers (node:internal/timers:514:7) {
      errno: -4039,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '2a03:2880:f11c:8083:face:b00c:0:25de',
      port: 443
    },
    Error: connect ETIMEDOUT 31.13.85.2:443
        at createConnectionError (node:net:1647:14)
        at afterConnectMultiple (node:net:1677:16) {
      errno: -4039,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '31.13.85.2',
      port: 443
    }
  ],
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 1000000000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'multipart/form-data; boundary=--------------------------816311197227850683834144',
      'User-Agent': 'axios/1.7.2',
      'Content-Length': '8781',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'https://ton-source-prod-2.herokuapp.com/prepareTactDeployment',
    data: FormData {
      _overheadLength: 331,
      _valueLength: 8394,
      _valuesToMeasure: [],
      writable: false,
      readable: true,
      dataSize: 0,
      maxDataSize: 2097152,
      pauseStreams: true,
      _released: true,
      _streams: [],
      _currentStream: null,
      _insideLoop: false,
      _pendingNext: false,
      _boundary: '--------------------------816311197227850683834144',
      _events: [Object: null prototype],
      _eventsCount: 3
    }
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Array],
      timeout: undefined,
      abort: undefined
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/prepareTactDeployment',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'ton-source-prod-2.herokuapp.com',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/prepareTactDeployment'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 8781,
    _requestBodyBuffers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '8781',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /prepareTactDeployment HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: multipart/form-data; boundary=--------------------------816311197227850683834144\r\n' +
        'User-Agent: axios/1.7.2\r\n' +
        'Content-Length: 8781\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: ton-source-prod-2.herokuapp.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/prepareTactDeployment',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'ton-source-prod-2.herokuapp.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://ton-source-prod-2.herokuapp.com/prepareTactDeployment',
    _timeout: null,
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: AggregateError
      at internalConnectMultiple (node:net:1117:18)
      at afterConnectMultiple (node:net:1684:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error] ]
  }
}

**Comment by ldbchang** [comment]
![福昕截屏20240625152922030](https://github.com/tact-lang/tact-template/assets/30137044/ebe75adf-7510-4e1e-8d6d-90679fc3a140)

**Comment by anton-trunov** [comment]
This looks like a network/service issue, not specific to tact-template
