### ISSUE TITLE
yarn add @tact-lang/compiler


### ISSUE THREAD

**Issue by Spider197350** [tact-lang/tact-template#4]

**Comment by anton-trunov** [comment]
@Spider197350 Would you mind adding more details here? What seems to be an issue here?

**Comment by Spider197350** [comment]
I am kinda new at all of this. I am trying to figure out a way to get to threw my passcodes, patterns, and frazes on my lab top, phones computer ect. I know that there are programs I can right to do it I just haveing a hard time getting a hold of them because everybody has ruined the ability to access them cause they use them for the wrong reasons. I have built web pages and written some code that I've learned through GitHub and other writable programs. But I'm just tired of getting locked out of certain things and not be able to access them. When I know that it can be done, I used to have a program on my computer that would go right through a phone. The only problem was is you lose everything on it which I didn't care. I was still able to get through the passcode on my phone and still use my phone. I'm just looking for back door code or any type of code I could write. Give me what it is that I'm trying to achieve.
I don't know if you can help me, But anything would be great. I know you probably have to make me work for it which I'm willing to do links other programmers any knowledge I will take thank you.
